CREATE DATABASE BOOKSMANAGER
GO 
USE BOOKSMANAGER
GO

CREATE TABLE BOOKS
(
	ID INT,
	BOOK_NAME VARCHAR(200),
	AUTHOR VARCHAR(200),
	BOOK_TYPE VARCHAR(200),
	PRIMARY KEY(ID)
)
GO

CREATE TABLE MEMBERS(
	USERNAME VARCHAR(150),
	PASS_WORD VARCHAR(255),
	PRIMARY KEY (USERNAME)
)
GO
 
INSERT INTO BOOKS (ID, BOOK_NAME, AUTHOR, BOOK_TYPE) VALUES(1,'CONG NGHE THONG TIN', 'KHOA HOC TU NHIEN', 'TAI LIEU') 
INSERT INTO BOOKS (ID, BOOK_NAME, AUTHOR, BOOK_TYPE) VALUES(2,'THE GODFATHER', 'MARIO PUZO', 'NOVEL') 
GO
INSERT INTO BOOKS (ID, BOOK_NAME, AUTHOR, BOOK_TYPE) VALUES(3,'FRANKENSTEIN', 'MARY SHELLY', 'NOVEL') 
GO
INSERT INTO BOOKS (ID, BOOK_NAME, AUTHOR, BOOK_TYPE) VALUES(4,'THE PRICE OF SALT', 'PATRICIA HIGHSMITH', 'NOVEL')
GO

INSERT INTO MEMBERS(USERNAME, PASS_WORD) VALUES('jay', 'new')
GO
